-- Crear una tabla
CREATE TABLE "USERS" (
    "UUID" UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    "NAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "MODIFIED_AT" TIMESTAMP,
    "LAST_LOGIN" TIMESTAMP,
    "TOKEN" VARCHAR(255),
    "IS_ACTIVE" BOOLEAN DEFAULT TRUE
);

CREATE TABLE "PHONES" (
    "PHONE_ID" INTEGER PRIMARY KEY AUTO_INCREMENT,
    "UUID" VARCHAR(255),
    "NUMBER" VARCHAR(20) NOT NULL,
    "CITY_CODE" VARCHAR(10) NOT NULL,
    "COUNTRY_CODE" VARCHAR(10) NOT NULL,
    FOREIGN KEY ("UUID") REFERENCES "USERS"("UUID")
);